name: Check Code Coverage

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  pull-requests: write
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        id: run_tests
        run: ./gradlew :app:testDebugUnitTest
        continue-on-error: true

      - name: Generate kover coverage report
        run: ./gradlew :app:koverXmlReportDebug

      - name: Get list of changed files
        id: changed_files
        uses: tj-actions/changed-files@v44

      - name: Analyze untested classes and coverage in changed files
        run: |
          echo "### ðŸ“Š Code Coverage Report" > report.md
          echo "" >> report.md
          
          if [[ "${{ steps.run_tests.outcome }}" == "failure" ]]; then
            echo "âŒ **Tests failed! Please check and fix them.**" >> report.md
          else
            echo "âœ… **All tests passed!**" >> report.md
          fi
          done

      - name: Post coverage report as PR comment
        uses: mshick/add-pr-comment@v2
        with:
          message-path: report.md
          refresh-message-position: true

      - name: Fail if tests failed
        if: steps.run_tests.outcome == 'failure'
        run: exit 1